[package]
name = "rust-htmlx-starter"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
handlebars = {version = "4.3.7", features = ["dir_source"] }
serde_json = "1.0.103"
tera = "1.19.0"
