[package]
name = "rusty-admin"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
askama = "0.14"
futures-util = { version = "0.3", features = [] }

[package.metadata.askama]
dir = "static"


